
[yeastar]
host = 192.168.40.18
https = false

username = api
password = some password

#password must be in clear text here since the app is going to generate MD5 on run
user and pass are configured in General for s100 Yeastart API must be enabled
